version: '3.6'

services:
  app:
    build: .
    entrypoint: java -server -jar kwaf.jar
    depends_on:
      - pg
    env_file:
      - .env
    ports:
      - 8080:8080
  pg:
    image: postgres:10.4
    volumes:
      - kwaf_pg_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  kwaf_pg_data:
    external: true
